Unix nfs
companieshouse/chl-tuxedo-terraform pull request #57
Opened 2022-04-21 07:58 UTC by samh241

adding nfs to setup

2022-04-28 10:28 UTC, marcransome requested changes

2022-04-28 10:28 UTC, marcransome commented on roles/deploy/tasks/nfs.yml
> +    path: "{{item.path}}"
Add spaces around the variable names here to be consistent with convention and the remainder of our code:

```suggestion
    src: "{{ item.src }}"
    path: "{{ item.path }}"
```

2022-04-28 10:28 UTC, marcransome commented on roles/deploy/tasks/nfs.yml
> +  yum: name=nfs-utils state=latest
Use native YAML syntax here rather than the shortened form. It's generally easier to read, plays nicer with syntax highlighting, and is the convention we follow in most projects:

```suggestion
- name: Install nfs-utils
  yum:
    name: nfs-utils
    state: latest
```

2022-04-28 10:28 UTC, marcransome commented on roles/deploy/tasks/nfs.yml
> +
The `nfsmounts` variable here will be ignored as it isn't used by the `yum` module. We'll need to define this elsewhere, either as a role default or as a host/group variable. The latter would be preferable in this case, as mount points will likely need to be scoped to each environment. We can achieve this by using tags to target specific environments in our dynamic inventory. For example, to define mount points for the `live` environment:

In `group_vars/tag_Environment_live.yml`

```yaml
nfsmounts:
  - path: "/home/scud/downloadchd/email"
    src: "ipo-file-svm-lif-be1.internal.ch:chd_image"
  - path: "/home/scud/downloadceu/email"
    src: "ipo-file-svm-lif-be1.internal.ch:chcc_email"
  - path: "/home/scud/downloadwck/email"
    src: "ipo-file-svm-lif-be1.internal.ch:wck_image"
  - path: "/home/scud/downloadceu/post"
    src: "ipo-file-svm-lif-be1.internal.ch:chcc_post"
  - path: "/data1/apps/scud"
    src: "ipo-file-svm-lif-be1.internal.ch:scanning"
  - path: "/data1/home/scanning"
    src: "ipo-file-svm-lif-be1.internal.ch:tiffexport"
  - path: "/data1/image/scud"
    src: "ipo-file-svm-lif-be1.internal.ch:tiffexport"
```

The dynamic inventory configuration files will also need to be updated to introduce a new keyed group. For example, in `inventory/heritage_live_aws_ec2.yml`:

```yaml
keyed_groups:
  - key: tags.Environment
    prefix: tag_Environment_
    separator: ""
```

2022-04-28 10:28 UTC, marcransome commented on roles/deploy/tasks/main.yml
> +
It's likely we will want this to be optional dependent on the presence of configuration for NFS mounts:

```suggestion
- include_tasks: nfs.yml
  when: nsfmounts is defined and nsfmounts | length > 0
```

2022-04-28 10:28 UTC, marcransome commented on roles/deploy/tasks/nfs.yml
> +  with_items: "{{nfsmounts}}"
As above, introduce some whitespace here for consistency:

```suggestion
  with_items: "{{ nfsmounts }}"
```

2022-05-03 12:56 UTC, Jata2k approved these changes

2022-05-03 12:57 UTC, marcransome approved these changes

2022-05-03 12:58 UTC, merged